### PR TITLE
Semantic linefeed feature

### PR DESCRIPTION
**Pull request by evandrocoan**
Fixes https://github.com/ehuss/Sublime-Wrap-Plus/issues/64 Semantic line wrapping support

Posted also on: https://forum.sublimetext.com/t/semantic-linefeed-wrapping-linewrap/33197

### CODE REVIEW

**Comment by yrammos** [comment]
Thanks! I hope this does get merged into @ehuss's great package.

**Comment by ehuss** [comment]
Thanks for the PR!  I noticed you added some more commits, I'm wondering if you are all finished now?
  There are a few changes I'd like to see before merging it.  I can work on it if you'd like.  In general:

* Move the tests to a separate "tests" directory and use the [Unittesting](https://github.com/randy3k/UnitTesting) package to run the tests.
* Is there a reason to change the name of the command?
* I'd like to add a config setting that controls the after-wrap behavior.  Perhaps something like `WrapPlus.after_wrap`.  This should be a string for the different behaviors.  The current behavior would be something like `"cursor_below"` and this new behavior would be something like `"cursor_stay"`.  The reason I haven't added this yet is because the proposed change doesn't completely work correctly (the reformatting will cause the cursor to jump a few characters based on what is added/inserted).  But I guess something is better than nothing.  A better solution is quite tricky, but perhaps I'll give it another shot soon.
* Prefix the new settings with `semantic_` to make it clear they only work if semantic wrapping is enabled.
* Is there a particular reason to change the long/hyphen default settings?  I don't really care one way or the other, just curious.

**Comment by evandrocoan** [comment]
> Is there a particular reason to change the long/hyphen default settings?

They seemed dangerous.


> Prefix the new settings with semantic_ to make it clear they only work if semantic wrapping is enabled.

Done on https://github.com/ehuss/Sublime-Wrap-Plus/pull/65/commits/7e7fa1f64093e4abd0b76ec511f6f187362cf1f8


> I'd like to add a config setting that controls the after-wrap behavior. Perhaps something like WrapPlus.after_wrap. 

Done on https://github.com/ehuss/Sublime-Wrap-Plus/pull/65/commits/07ac35194ae601b76b92f78b00d4336384979794


> Is there a reason to change the name of the command?

I had did it because I did a long time ago because I did not knew how to change the class code to implement the cursor stay feature. Now I removed it and restored it as I implemented the code directly on the main code.


> Move the tests to a separate "tests" directory and use the Unittesting package to run the tests.

Done on https://github.com/ehuss/Sublime-Wrap-Plus/pull/65/commits/b5886f6cc8e1f53921579c97177f77ef22331190

**Comment by evandrocoan** [comment]
I implemented the unit test system by https://github.com/randy3k/UnitTesting, these are the results:
``` 
test_balance_characters_between_line_wraps_ending_with_long_word (semantic_linefeed_unit_tests.LineBalancingUnitTests) ... ok
test_balance_characters_between_line_wraps_with_trailing_new_line (semantic_linefeed_unit_tests.LineBalancingUnitTests) ... ok
test_balance_characters_between_line_wraps_without_trailing_new_line (semantic_linefeed_unit_tests.LineBalancingUnitTests) ... ok
test_split_lines_with_trailing_new_line (semantic_linefeed_unit_tests.LineBalancingUnitTests) ... ok
test_split_lines_with_very_long_line_and_word (semantic_linefeed_unit_tests.LineBalancingUnitTests) ... ok
test_split_lines_without_trailing_new_line (semantic_linefeed_unit_tests.LineBalancingUnitTests) ... ok
test_is_command_separated_list (semantic_linefeed_unit_tests.SemanticLineWrapUnitTests) ... ok
test_is_command_separated_list_lowerbound (semantic_linefeed_unit_tests.SemanticLineWrapUnitTests) ... ok
test_is_command_separated_list_upperbound (semantic_linefeed_unit_tests.SemanticLineWrapUnitTests) ... ok
test_semantic_line_wrap_ending_with_comma_list (semantic_linefeed_unit_tests.SemanticLineWrapUnitTests) ... ok
test_semantic_line_wrap_long_word (semantic_linefeed_unit_tests.SemanticLineWrapUnitTests) ... ok
test_semantic_line_wrap_simple_sentences (semantic_linefeed_unit_tests.SemanticLineWrapUnitTests) ... ok
test_semantic_line_wrap_with_79_characters (semantic_linefeed_unit_tests.SemanticLineWrapUnitTests) ... ok
test_semantic_line_wrap_with_80_characters (semantic_linefeed_unit_tests.SemanticLineWrapUnitTests) ... ok
test_semantic_line_wrap_with_81_characters (semantic_linefeed_unit_tests.SemanticLineWrapUnitTests) ... ok
test_semantic_line_wrap_with_81_characters_on_list_flushing (semantic_linefeed_unit_tests.SemanticLineWrapUnitTests) ... ok
test_semantic_line_wrap_with_comma_list_on_the_end (semantic_linefeed_unit_tests.SemanticLineWrapUnitTests) ... ok
test_semantic_line_wrap_with_comma_list_on_the_middle (semantic_linefeed_unit_tests.SemanticLineWrapUnitTests) ... ok
test_semantic_line_wrap_with_initial_indentation (semantic_linefeed_unit_tests.SemanticLineWrapUnitTests) ... ok
test_semantic_line_wrap_with_long_word_at_comma_list_end (semantic_linefeed_unit_tests.SemanticLineWrapUnitTests) ... ok
test_semantic_line_wrap_with_numeric_comma_list_on_the_end (semantic_linefeed_unit_tests.SemanticLineWrapUnitTests) ... ok

----------------------------------------------------------------------
Ran 21 tests in 0.560s

OK

UnitTesting: Done.
```

But I also kept the caller on `plugin_loaded()` as a comment because I would like to use it.


> I'm wondering if you are all finished now?

Yes, unless some bug emerges.


>  The reason I haven't added this yet is because the proposed change doesn't completely work correctly (the reformatting will cause the cursor to jump a few characters based on what is added/inserted)

I noticed this sometimes, but the current implementation is already very good as it is, which is much better then sending my cursor to the end of the line (far away from where it is).

This is a problem because I call several times the command `Ctrl+Q` while I am writing text, then it is really boring to be sending it to the end of the paragraph. If a few time the cursor move a little off, it is not a problem compared to sending it to the end of the line always.

**Comment by evandrocoan** [comment]
I just pushed a few things I forgot to remove/add. This should be the end.

**Comment by ehuss** [comment]
Sweet!  I have to head out today, but I will try to test it soon.

**Comment by evandrocoan** [comment]
Closing if favor of #66 All my updates

**Pull request closed without merging**
